version: '3'
services:
  mongodb:
    build:
      context: mongodb
    image: mongo:6
    networks:
      - sandbox-site-network
  # web:
  #   build: 
  #     context: web
  #   image: eclipse-temurin:17-jdk-alpine
  #   networks:
  #     - sandbox-site-network
  user:
    build: 
      context: user
    image: node:18
    depends_on:
      - mongodb
    networks:
      - sandbox-site-network
    ports:
      - 8080:8080
    environment:
      - USER_SERVER_PORT=8080
      - MONGO_URL=mongodb://mongodb:27017/users

networks:
  sandbox-site-network: