version: '3'
services:
  web:
    build:
      context: web
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SESSION_SECRET=change_me_later
      - USER_SERVER_BASE=http://user:8080
    networks:
      - sandbox-site-network
    depends_on:
      - user
      - mongodb
  mongodb:
    build:
      context: mongodb
    networks:
      - sandbox-site-network
  user:
    build: 
      context: user
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/users
      - PORT=8080
    networks:
      - sandbox-site-network

networks:
  sandbox-site-network: